apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
    - name: github
      mappingMethod: claim
      type: GitHub
      github:
        clientID: YOUR_GITHUB_CLIENT_ID
        clientSecret:
          name: github-secret
        hostname: ""  # Leave empty for github.com, set for GitHub Enterprise
        organizations:
          - your-org-name

